### ISSUE TITLE
WAR changedError

### ISSUE THREAD

**Issue by archiolochos** [nicoh88/homebridge-xiaomi-roborock-vacuum#93] opened 2020-01-31 08:26 UTC
Hallo nicoh88,

i found an error in my logfile i dont know what to do with:
"WAR changedError | rockrobo.vacuum.v1 | Robot has an ERROR - charger-offline, Charger is offline"

what does that error mean? 
whats a WAD that changed? 
i have got a lot of this errors in my log - do i need to care?

**Comment by afharo** [comment] 2020-01-31 10:14
Hi @archiolocho 
We are looking into this in #91 

Duplicate of #91

**Comment by afharo** [comment] 2020-01-31 10:15
If you don’t mind I’ll close this one to have a bit of clean list of pending tasks

**Closed** 2020-01-31 10:14 UTC

**Comment by nicoh88** [comment] 2020-01-31 10:55
@archiolochos Is the charger unplugged? for sure?

@afharo For me, the charging station was really unplugged! But #91 still open.

**Comment by afharo** [comment] 2020-01-31 11:21
> But problems in #91 still open.

Yes, I'll try to tackle it sometime this weekend :)

**Comment by nicoh88** [comment] 2020-02-01 12:37
Fixed, waiting on version 0.6.6 or test the #master (0.6.6-dev) branch.

```
sudo su -
npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master

```
