### ISSUE TITLE
S5 with FW3.5.7 Room Switch toggle bug

### ISSUE THREAD

**Issue by github9984** [nicoh88/homebridge-xiaomi-roborock-vacuum#138] opened 2020-03-29 00:51 UTC
To replicate the issue.

1. Turn on Room toggle. The Vacuum fan speed value doesn't update.
2. Get out of HomeKit, come back in. The app will do an "update", and both Vacuum Fan and Room Toggle will be off.
3. The Fan Speed will sometimes come back with a value, but disappears on / off.

There's no way to tell what Room is being currently cleaned.

**Comment by afharo** [comment] 2020-04-24 22:01
Duplicate of #119

**Closed by afharo** 2020-04-24 22:01 UTC
