### ISSUE TITLE
Vacuum only starting after second attempt 

### ISSUE THREAD

**Issue by Tim2309** [nicoh88/homebridge-xiaomi-roborock-vacuum#72] opened 2019-10-28 07:56 UTC
Since the new update 0.6.3 I got problems with my roborock S6.
If I want to start it in the home app, I got a connection problem after a few seconds, if I start it again with the "!" in the home app the vacuum starts cleaning. After that every start and stop works directly.
A few hours later the same problem again. The log isn't very helpful, only thing you can see is that I startet it 2 times.
With the last version 0.6.2 I didn't notice these problems.

[10/28/2019, 8:51:03 AM] [Roborock] ACT setCleaning | roborock.vacuum.s6 | Start cleaning, not charging.
[10/28/2019, 8:51:21 AM] [Roborock] ACT setCleaning | roborock.vacuum.s6 | Start cleaning, not charging.
[10/28/2019, 8:51:22 AM] [Roborock] INF changedCleaning | roborock.vacuum.s6 | Cleaning is ON.

**Comment by Tim2309** [comment] 2019-10-28 18:10
I also noticed a second problem:
if I Stop the vacuum manually in the home app the robot says spot cleaning and then it stops. The robot won't drive back to the dock.
With my old 1gen Xiaomi this worked fine in 0.6.2

Should I open a second issue for this?

[10/28/2019, 7:06:23 PM] [Staubsauger] INF changedCleaning | roborock.vacuum.s6 | Cleaning is ON.
[10/28/2019, 7:06:40 PM] [Staubsauger] ACT setCleaning | roborock.vacuum.s6 | Stop cleaning and go to charge.
[10/28/2019, 7:06:41 PM] [Staubsauger] INF changedCleaning | roborock.vacuum.s6 | Cleaning is OFF.

**Comment by afharo** [comment] 2019-11-13 02:28
Thank you for your insights, @Tim2309 and sorry for the delay.
I’ll have a look at it sometime this week.

**Comment by afharo** [comment] 2019-11-13 02:30
Additional question: @Tim2309 do you have the Pause switch enabled?

**Comment by Tim2309** [comment] 2019-11-13 06:09
Thank you for helping.
I activated the pause switch after I discovered the problem.
Its the same with/without the switch.

**Comment by Tim2309** [comment] 2019-11-18 11:46
Update:
The last 2 weeks it worked without starting problems, maybe it was a xiaomi server issue? Or is the command executed locally?

The problem discribed in my second message with spot cleaning persists.

**Comment by afharo** [comment] 2019-11-18 22:22
Thank you for the update. 
I’ll focus on the pausing/spot cleaning issue. Thanks

**Comment by Tim2309** [comment] 2019-11-18 22:36
Ok perfect, i hope you understand the problem in the correct way:
On->vacuum is cleaning
Off->vacuum say Spot cleaning but does nothing 

On->vacuum is cleaning 
Pause->pause 
Off->vacuum is going back to dock

**Comment by Tim2309** [comment] 2019-11-23 17:15
Since two days the starting problem appeared again.
First time i got a timeout. After reloading HomeKit app the vacuum is off, then it‘s possible to start it.

**Comment by afharo** [comment] 2019-12-20 18:44
The pause issue will be dealt with in the specific issue where we are discussing about it.
Duplicate of #73

**Closed by afharo** 2019-12-20 18:44 UTC
